require "user.options"
require "user.plugins"
require "user.themery"
require "user.theme"
require "user.cmp"
require "user.lsp"
require "user.autopairs"
require "user.bufferline"
require "user.nvimtree"
require "user.treesitter"
require "user.null-ls"
require "user.lualine"
require "user.toggleterm"
-- require "user.debugprint"
require "user.nvimdap"
require "user.keymaps"

-- test temporaire
